version: '3.8'
services:
  example-remote-debug:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.debug
    cap_add:
      - SYS_PTRACE
    ports:
      - "8081:8080"
      - "40000:40000"